name = "Aqua Clan"
license = "MIT"
licenselink = "https://github.com/aaronplayz-sys/Aqua-Clan/blob/main/LICENSE.md"
description = "A multi gaming clan."
homepage = "https://aquaclan.pages.dev/"
tags = ["gamers",
        "gaming",
        "clan",
        "development",
        "minecraft",
        "roblox",
        "portfolio"
        ]
features = ["projects", "gaming development", "events", "youtube content", "blog", "roblox",
            "minecraft", "rec room"]

[author]
  name = "Aaron Playz"
  homepage = "https://aaronplayzgaming.com/"
